import logging
import concurrent.futures
from deep_translator import GoogleTranslator

logger = logging.getLogger("backend.localization")

_translation_cache = {
    # Hindi Fallbacks
    "hi:AranyaSentinel AI": "अरण्यसेंटिनेल एआई",
    "hi:Comprehensive Forest Intelligence Report": "व्यापक वन खुफिया रिपोर्ट",
    "hi:Forest Region:": "वन क्षेत्र:",
    "hi:Generated Date:": "उत्पन्न तिथि:",
    "hi:Generated Time:": "उत्पन्न समय:",
    "hi:Generated By:": "उत्पन्नकर्ता:",
    "hi:Report ID:": "रिपोर्ट आईडी:",
    "hi:Executive Summary": "कार्यकारी सारांश",
    "hi:Metric": "मीट्रिक",
    "hi:Value": "मूल्य",
    "hi:Status": "स्थिति",
    "hi:Forest Health Score": "वन स्वास्थ्य स्कोर",
    "hi:Forest Loss": "वन हानि",
    "hi:Severity": "गंभीरता",
    "hi:Forest Information": "वन जानकारी",
    "hi:State:": "राज्य:",
    "hi:District:": "जिला:",
    "hi:Area:": "क्षेत्र:",
    "hi:Climate:": "जलवायु:",
    "hi:Major Species:": "प्रमुख प्रजातियां:",
    "hi:Satellite Analysis": "उपग्रह विश्लेषण",
    "hi:Analytics": "एनालिटिक्स",
    "hi:Historical Trend Analysis": "ऐतिहासिक प्रवृत्ति विश्लेषण",
    "hi:AI Summary": "एआई सारांश",
    "hi:Conclusion": "निष्कर्ष",
}

def _do_translate(text: str, target_lang: str) -> str:
    translator = GoogleTranslator(source='auto', target=target_lang)
    translated = translator.translate(text)
    return translated if translated else text

def translate_text(text: str, target_lang: str) -> str:
    """
    Translates raw text to the target language dynamically using deep-translator (free Google Translate API).
    Uses an in-memory cache and a strict timeout to prevent rate-limiting and hanging.
    """
    if target_lang == "en" or not text:
        return text
        
    cache_key = f"{target_lang}:{text}"
    if cache_key in _translation_cache:
        return _translation_cache[cache_key]
        
    try:
        # Prevent hanging by enforcing a 2-second timeout
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_do_translate, text, target_lang)
            result = future.result(timeout=2.0)
            
        _translation_cache[cache_key] = result
        return result
    except concurrent.futures.TimeoutError:
        logger.warning(f"Translation timed out for '{text[:20]}...'")
        _translation_cache[cache_key] = text
        return text
    except Exception as e:
        logger.error(f"Dynamic translation failed for '{text[:20]}...': {e}")
        _translation_cache[cache_key] = text
        return text
