from datetime import datetime

FOREST_KNOWLEDGE_DB = [
    {
        "forest_id": "satpura-tiger-reserve",
        "forest_name": "Satpura Tiger Reserve",
        "overview": "Nestled in the Mahadeo Hills of the Satpura range, this pristine ecosystem is known for its rugged terrain, deep gorges, and rich biodiversity. It offers a unique wilderness experience.",
        "state": "Madhya Pradesh",
        "district": "Hoshangabad",
        "country": "India",
        "area_sq_km": 2133.30,
        "established_year": 1981,
        "elevation_meters": "300 - 1352",
        "forest_type": "Tropical Moist Deciduous",
        "protected_status": "Tiger Reserve & National Park",
        "unesco_status": "Tentative List",
        "climate": "Subtropical",
        "average_rainfall_mm": 1350,
        "major_trees": ["Teak", "Sal", "Tendu", "Mahua", "Bel", "Bamboos"],
        "vegetation_type": "A transition zone with both Sal and Teak flora blending seamlessly.",
        "major_animals": ["Bengal Tiger", "Indian Leopard", "Sloth Bear", "Gaur", "Dhole", "Sambar"],
        "bird_species": ["Malabar Pied Hornbill", "Crested Serpent Eagle", "Paradise Flycatcher", "Peafowl"],
        "threatened_species": ["Sloth Bear", "Leopard", "Barasingha"],
        "endangered_species": ["Bengal Tiger", "Indian Wild Dog (Dhole)"],
        "rivers": ["Denwa", "Tawa"],
        "ecological_importance": "Acts as a crucial central Indian wildlife corridor connecting other major reserves.",
        "tourism_importance": "Famous for walking safaris, kayaking, and non-motorized eco-tourism.",
        "interesting_facts": ["Pachmarhi biosphere reserve encompasses Satpura.", "Only park in Central India offering walking safaris."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "kanha-national-park",
        "forest_name": "Kanha National Park",
        "overview": "The inspiration for Rudyard Kipling's 'The Jungle Book', Kanha is famous for its lush sal and bamboo forests and successful conservation of the Barasingha.",
        "state": "Madhya Pradesh",
        "district": "Mandla and Balaghat",
        "country": "India",
        "area_sq_km": 940.0,
        "established_year": 1955,
        "elevation_meters": "450 - 900",
        "forest_type": "Tropical Moist Dry Deciduous",
        "protected_status": "Tiger Reserve & National Park",
        "unesco_status": None,
        "climate": "Tropical",
        "average_rainfall_mm": 1800,
        "major_trees": ["Sal", "Saja", "Lendia", "Dhaora", "Tendu", "Palas", "Bija", "Mahua", "Aonla"],
        "vegetation_type": "Dense Sal forests interspersed with expansive grassy meadows (maidans).",
        "major_animals": ["Bengal Tiger", "Barasingha", "Leopard", "Sloth Bear", "Wild Dog", "Jackal"],
        "bird_species": ["Indian Roller", "Crested Hawk Eagle", "Black Ibis", "Little Grebe"],
        "threatened_species": ["Leopard", "Sloth Bear"],
        "endangered_species": ["Bengal Tiger", "Hard-ground Barasingha", "Dhole"],
        "rivers": ["Banjar", "Halon"],
        "ecological_importance": "Critical habitat for the recovery of the Hard-ground Barasingha, saving it from extinction.",
        "tourism_importance": "One of the most well-maintained and visited tiger reserves in India.",
        "interesting_facts": ["It was the first tiger reserve in India to officially introduce a mascot, 'Bhoorsingh the Barasingha'."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "pench-national-park",
        "forest_name": "Pench National Park",
        "overview": "Named after the pristine Pench River which flows through it, Pench is another muse for 'The Jungle Book' with its rich prey base and high tiger density.",
        "state": "Madhya Pradesh & Maharashtra",
        "district": "Seoni and Chhindwara",
        "country": "India",
        "area_sq_km": 758.0,
        "established_year": 1975,
        "elevation_meters": "425 - 620",
        "forest_type": "Southern Tropical Dry Deciduous",
        "protected_status": "Tiger Reserve & National Park",
        "unesco_status": None,
        "climate": "Tropical",
        "average_rainfall_mm": 1300,
        "major_trees": ["Teak", "Mahuwa", "Palas", "Bija", "Amaltas"],
        "vegetation_type": "Predominantly teak forests mixed with extensive bamboo tracts.",
        "major_animals": ["Bengal Tiger", "Leopard", "Jackal", "Peafowl", "Wild Dog", "Chital"],
        "bird_species": ["Pintail", "Lesser Whistling Teal", "Indian Pitta", "Osprey", "Grey-headed Fish Eagle"],
        "threatened_species": ["Sloth Bear", "Leopard"],
        "endangered_species": ["Bengal Tiger", "Indian Wolf"],
        "rivers": ["Pench"],
        "ecological_importance": "A vital link in the central Indian tiger landscape, acting as a source population for tigers.",
        "tourism_importance": "Highly popular for tiger sightings and bird watching.",
        "interesting_facts": ["BBC's 'Spy in the Jungle' documentary was filmed here.", "The park straddles two states: MP and Maharashtra."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "bandhavgarh-national-park",
        "forest_name": "Bandhavgarh National Park",
        "overview": "Known for having one of the highest known densities of Bengal tigers in the world, this park features ancient forts, caves, and steep ridges.",
        "state": "Madhya Pradesh",
        "district": "Umaria",
        "country": "India",
        "area_sq_km": 1536.0,
        "established_year": 1968,
        "elevation_meters": "410 - 810",
        "forest_type": "Tropical Moist Deciduous",
        "protected_status": "Tiger Reserve & National Park",
        "unesco_status": None,
        "climate": "Subtropical",
        "average_rainfall_mm": 1170,
        "major_trees": ["Sal", "Saja", "Tendu", "Arjun", "Amla", "Palas"],
        "vegetation_type": "Valleys covered with marshy grasslands surrounded by dense Sal forests on the lower slopes.",
        "major_animals": ["Bengal Tiger", "Leopard", "Sambar", "Barking Deer", "Nilgai", "Chinkara"],
        "bird_species": ["Plum-headed Parakeet", "Orange-headed Thrush", "Brown Fish Owl"],
        "threatened_species": ["Leopard"],
        "endangered_species": ["Bengal Tiger", "Dhole"],
        "rivers": ["Charanganga"],
        "ecological_importance": "Historically a hunting ground for Maharajas, now a highly protected, tiger-rich dense ecosystem.",
        "tourism_importance": "Considered the best place in the world to photograph wild tigers.",
        "interesting_facts": ["White tigers were originally discovered in the forests around this region (Rewa).", "Contains ancient man-made caves with Sanskrit inscriptions."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "tadoba-tiger-reserve",
        "forest_name": "Tadoba Andhari Tiger Reserve",
        "overview": "Often referred to as the 'Jewel of Vidarbha', Tadoba is Maharashtra's oldest and largest national park, famous for its excellent tiger sightings.",
        "state": "Maharashtra",
        "district": "Chandrapur",
        "country": "India",
        "area_sq_km": 1727.0,
        "established_year": 1955,
        "elevation_meters": "200 - 350",
        "forest_type": "Southern Tropical Dry Deciduous",
        "protected_status": "Tiger Reserve",
        "unesco_status": None,
        "climate": "Tropical hot",
        "average_rainfall_mm": 1200,
        "major_trees": ["Teak", "Ain", "Bija", "Dhauda", "Haldu", "Salai", "Semal"],
        "vegetation_type": "Southern tropical dry deciduous forest with dense woodlands and bamboo thickets.",
        "major_animals": ["Bengal Tiger", "Leopard", "Sloth Bear", "Gaur", "Nilgai", "Dhole", "Striped Hyena"],
        "bird_species": ["Crested Serpent Eagle", "Grey-headed Fish Eagle", "Changeable Hawk-Eagle"],
        "threatened_species": ["Sloth Bear"],
        "endangered_species": ["Bengal Tiger", "Dhole"],
        "rivers": ["Andhari", "Erai"],
        "ecological_importance": "Acts as a critical breeding ground for tigers dispersing into central India.",
        "tourism_importance": "Renowned for its 'Maya' and 'Matkasur' tigers; very high visitor success rate.",
        "interesting_facts": ["The name 'Tadoba' comes from the god 'Taru' worshipped by local tribes."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "gir-national-park",
        "forest_name": "Gir National Park",
        "overview": "The sole home of the Asiatic lion in the wilderness, Gir is a rugged expanse of dry scrubland, savanna, and rocky hills in Gujarat.",
        "state": "Gujarat",
        "district": "Junagadh, Gir Somnath, Amreli",
        "country": "India",
        "area_sq_km": 1412.0,
        "established_year": 1965,
        "elevation_meters": "150 - 530",
        "forest_type": "Dry Deciduous & Scrub",
        "protected_status": "National Park & Wildlife Sanctuary",
        "unesco_status": "Tentative List",
        "climate": "Semi-Arid",
        "average_rainfall_mm": 1000,
        "major_trees": ["Teak", "Acacia", "Zizyphus", "Banyan", "Jamun", "Tendu"],
        "vegetation_type": "Teak-dominated dry deciduous interspersed with acacia scrub and savanna.",
        "major_animals": ["Asiatic Lion", "Indian Leopard", "Chital", "Nilgai", "Chinkara", "Four-horned Antelope"],
        "bird_species": ["Indian Vulture", "Tawny Eagle", "Brown Fish Owl", "Indian Peafowl"],
        "threatened_species": ["Mugger Crocodile", "Four-horned Antelope"],
        "endangered_species": ["Asiatic Lion", "Indian Vulture"],
        "rivers": ["Hiran", "Shetrunji", "Datardi", "Shingoda"],
        "ecological_importance": "The last refuge of the Asiatic Lion, saving it from the brink of extinction.",
        "tourism_importance": "The only place outside Africa to see wild lions.",
        "interesting_facts": ["The park also has the largest population of leopards in India.", "Home to the Maldhari tribes who co-exist with lions."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "kaziranga-national-park",
        "forest_name": "Kaziranga National Park",
        "overview": "A vast expanse of tall elephant grass, marshland, and dense tropical moist broadleaf forests, crisscrossed by four major rivers including the Brahmaputra.",
        "state": "Assam",
        "district": "Golaghat, Nagaon, Sonitpur",
        "country": "India",
        "area_sq_km": 858.98,
        "established_year": 1908,
        "elevation_meters": "40 - 80",
        "forest_type": "Tropical Moist Broadleaf",
        "protected_status": "National Park & Tiger Reserve",
        "unesco_status": "World Heritage Site",
        "climate": "Subtropical Monsoon",
        "average_rainfall_mm": 2220,
        "major_trees": ["Kumbhi", "Indian Gooseberry", "Cotton Tree", "Elephant Apple"],
        "vegetation_type": "Alluvial inundated grasslands, tropical wet evergreen forests, and tropical semi-evergreen forests.",
        "major_animals": ["Indian Rhinoceros", "Asian Elephant", "Wild Water Buffalo", "Bengal Tiger", "Swamp Deer"],
        "bird_species": ["Great Indian Hornbill", "Pallas's Fish Eagle", "Bengal Florican"],
        "threatened_species": ["Wild Water Buffalo", "Swamp Deer"],
        "endangered_species": ["Indian Rhinoceros", "Asian Elephant", "Bengal Tiger", "Gangetic Dolphin"],
        "rivers": ["Brahmaputra", "Diphlu", "Mora Diphlu", "Mora Dhansiri"],
        "ecological_importance": "Hosts two-thirds of the world's great one-horned rhinoceroses and is a major birding hotspot.",
        "tourism_importance": "A globally recognized wildlife destination offering elephant and jeep safaris.",
        "interesting_facts": ["Kaziranga boasts the highest density of tigers among protected areas in the world.", "Floods annually, which is vital for maintaining the ecosystem."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "sundarbans",
        "forest_name": "Sundarbans National Park",
        "overview": "The largest mangrove forest in the world, formed by the confluence of the Ganges, Brahmaputra, and Meghna Rivers in the Bay of Bengal.",
        "state": "West Bengal",
        "district": "South 24 Parganas, North 24 Parganas",
        "country": "India",
        "area_sq_km": 1330.10,
        "established_year": 1984,
        "elevation_meters": "0 - 10",
        "forest_type": "Mangrove Forest",
        "protected_status": "National Park, Tiger Reserve & Biosphere Reserve",
        "unesco_status": "World Heritage Site",
        "climate": "Tropical Monsoon",
        "average_rainfall_mm": 1920,
        "major_trees": ["Sundari", "Gewa", "Keora", "Golpata", "Goran"],
        "vegetation_type": "Dense tidal mangrove forests adapted to saline and brackish water.",
        "major_animals": ["Bengal Tiger", "Estuarine Crocodile", "Fishing Cat", "Spotted Deer", "Wild Boar"],
        "bird_species": ["Masked Finfoot", "Mangrove Pitta", "Brown-winged Kingfisher", "White-bellied Sea Eagle"],
        "threatened_species": ["Fishing Cat", "Irrawaddy Dolphin"],
        "endangered_species": ["Bengal Tiger", "Estuarine Crocodile", "Northern River Terrapin"],
        "rivers": ["Ganges", "Brahmaputra", "Meghna", "Matla", "Bidya"],
        "ecological_importance": "Acts as a vital protective barrier for inland areas against cyclones and tidal surges.",
        "tourism_importance": "Unique boat safaris; a mysterious and challenging environment for tiger spotting.",
        "interesting_facts": ["Tigers here are known for their exceptional swimming abilities and man-eating tendencies.", "Named after the 'Sundari' tree."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "jim-corbett",
        "forest_name": "Jim Corbett National Park",
        "overview": "India's oldest national park, nestled in the Himalayan foothills. Known for its breathtaking landscapes and the pioneering Project Tiger.",
        "state": "Uttarakhand",
        "district": "Nainital and Pauri Garhwal",
        "country": "India",
        "area_sq_km": 520.8,
        "established_year": 1936,
        "elevation_meters": "385 - 1100",
        "forest_type": "Moist Deciduous & Himalayan Subtropical Pine",
        "protected_status": "National Park & Tiger Reserve",
        "unesco_status": "Tentative List",
        "climate": "Subtropical",
        "average_rainfall_mm": 2135,
        "major_trees": ["Sal", "Khair", "Sissoo", "Chir Pine", "Rohini", "Haldu"],
        "vegetation_type": "Diverse mix of riverine belts, marshy depressions, grasslands, and large lakes.",
        "major_animals": ["Bengal Tiger", "Asian Elephant", "Leopard", "Sambar Deer", "Himalayan Black Bear", "Yellow-throated Marten"],
        "bird_species": ["Crested Kingfisher", "Great Hornbill", "Wallcreeper", "Ibisbill"],
        "threatened_species": ["Himalayan Black Bear", "Gharial"],
        "endangered_species": ["Bengal Tiger", "Asian Elephant", "Gharial"],
        "rivers": ["Ramganga", "Kosi"],
        "ecological_importance": "A crucial habitat for the conservation of the tiger and the Asian elephant in the sub-Himalayan belt.",
        "tourism_importance": "A premier ecotourism destination, especially the Dhikala zone.",
        "interesting_facts": ["Originally established as Hailey National Park.", "First park to come under the Project Tiger initiative in 1973."],
        "last_updated": datetime.now().isoformat()
    },
    {
        "forest_id": "ranthambore",
        "forest_name": "Ranthambore National Park",
        "overview": "A former royal hunting ground bounded by the Banas and Chambal rivers. Famous for its imposing 10th-century fort and diurnal tigers.",
        "state": "Rajasthan",
        "district": "Sawai Madhopur",
        "country": "India",
        "area_sq_km": 1334.0,
        "established_year": 1980,
        "elevation_meters": "215 - 505",
        "forest_type": "Tropical Dry Deciduous & Scrub",
        "protected_status": "National Park & Tiger Reserve",
        "unesco_status": "World Heritage Site (Fort)",
        "climate": "Subtropical Dry",
        "average_rainfall_mm": 800,
        "major_trees": ["Dhok", "Banyan", "Pipal", "Neem", "Babul", "Gum"],
        "vegetation_type": "Dry deciduous forests and open grassy meadows, highly adapted to arid conditions.",
        "major_animals": ["Bengal Tiger", "Indian Leopard", "Nilgai", "Wild Boar", "Sambar", "Mugger Crocodile", "Sloth Bear"],
        "bird_species": ["Indian Courser", "Sarus Crane", "Painted Spurfowl", "Indian Peafowl"],
        "threatened_species": ["Sloth Bear", "Mugger Crocodile"],
        "endangered_species": ["Bengal Tiger", "Dhole"],
        "rivers": ["Banas", "Chambal"],
        "ecological_importance": "One of the most significant tiger reserves in the relatively arid western region of India.",
        "tourism_importance": "World-renowned for its highly visible and fearless tigers roaming amongst ancient ruins.",
        "interesting_facts": ["Tigers here are known to hunt during the day.", "The legendary tigress Machali, the most photographed tiger, lived here."],
        "last_updated": datetime.now().isoformat()
    }
]
